MODE_SOUND_BAR = 1
MODE_SOUND_ROUTE = 2
MODE_RANDOM_COLOR = 3
MODE_OFF = 4

MODES = [MODE_SOUND_BAR,
         MODE_SOUND_ROUTE,
         MODE_RANDOM_COLOR,
         MODE_OFF]

DEFAULT_MAX_BRIGHT = 20
DEFAULT_VOLUME_SENSITIVITY = 4
